SQLisHard/Models/Exercise.cs
using SQLisHard.Domain.Exercises;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SQLisHard.Models
{
	public class Exercise
	{
		public string Id { get; set; }
		public string Title { get; set; }
		public string Details { get; set; }
		public string Explanation { get; set; }
		public string Example { get; set; }
		public string ExerciseDescription { get; set; }

		public Exercise() { }

		public Exercise(DefinedExercise exercise)
		{
			Id = exercise.Id;
			Title = exercise.Title;
			Explanation = exercise.Explanation;
			Example = exercise.Example;
			ExerciseDescription = exercise.Exercise;

			//TODO remove after a few pushes as part of removing details from client
			Details = exercise.Explanation + "\n" + exercise.Example + "\n" + exercise.Exercise;
		}
	}
}

SQLisHard/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SQLisHard.Controllers
{
    public class AboutController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Exercises()
		{
			return View();
		}

		public ActionResult Tech()
		{
			return View();
		}

    }
}

SQLisHard/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SQLisHard.Controllers
{
    public class ExerciseController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Old()
		{
			return View();
		}

    }
}

SQLisHard/Controllers/ExercisesController.cs
using SQLisHard.Domain.Exercises;
using SQLisHard.Domain.QueryEngine;
using SQLisHard.Domain.QueryEngine.DatabaseExecution;
using SQLisHard.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SQLisHard.Controllers
{
	public class ExercisesController : ApiController
	{
		IExerciseStore _exerciseStore;

		public ExercisesController() : this(MvcApplication.ExerciseStore) { }
		public ExercisesController(IExerciseStore exerciseStore)
		{
			_exerciseStore = exerciseStore;
		}

		[HttpGet]
		public ExerciseSet List(string exerciseSetId = "")
		{
			var definedExercise = _exerciseStore.GetList(exerciseSetId);
			return new ExerciseSet(definedExercise);
		}
	}

}

SQLisHard/Views/About/Exercises.cshtml
@{
    ViewBag.Title = "Learning SQL - The Exercises";

}
<div class="about">
    <div class="banner">
        <h1>SQL is Hard</h1>
        <ul>
            <li>@Html.ActionLink("The Goal","","About")</li>
            <li class="selected">@Html.ActionLink("The Exercises","Exercises","About")</li>
            <li>@Html.ActionLink("The Tech","Tech","About")</li>
@*            <li>@Html.ActionLink("Updates","Updates","About")</li>*@
        </ul>
    </div>
    <h2>Current Exercises</h2>
    <p>
    The first set of exercises is designed around SELECTing data from the database, starting from nothing
    and progressing through sorting, multiple table JOINs, and data aggregation with methods such as SUM 
    and AVG.
    </p>
    <p>
    At the moment, I have only added the first few exercises in this set, enough to help me build out the 
    interface and infrastructure. With those in place, I'll be moving on to finish out this first Exercise Set.
    </p>
    <h2>Future Exercise Sets</h2>
    <p>
    Once the first exercise set is stable, I'm going to move on to defining new sets of exercises. Ideas 
    I've been playing with include:
    <ul>
        <li>Windowing functions</li>
        <li>Common Table Expressions</li>
        <li>Performance Tuning (Capturing plans and STATISTICS IO output, if possible)</li>
        <li>Using INFORMATION_SCHEMA and System Tables</li>
        <li>INSERT/UPDATE/DELETE statements</li>
        <li>Programming Challenges</li>
    </ul>
    </p>
    <p>
    Mixed in will be additional features, depending on the number of people using the site, levels of
    experience, and so on. Performance improvements ay prove necessary, additional functionality to
    support some of the new exercise sets above will probably be required, and some ability to save
    and review past progress are all items on the backlog.
    </p>

</div>

SQLisHard/Views/About/Index.cshtml
@{
    ViewBag.Title = "Learning SQL";

}
<div class="about">
    <div class="banner">
        <h1>SQL is Hard</h1>
        <ul>
            <li class="selected">@Html.ActionLink("The Goal","","About")</li>
            <li>@Html.ActionLink("The Exercises","Exercises","About")</li>
            <li>@Html.ActionLink("The Tech","Tech","About")</li>
@*            <li>@Html.ActionLink("Updates","Updates","About")</li>*@
        </ul>
    </div>
    <p>
    I learned SQL the hard way. Some basic MySQL and design in college, a little MS Access on the side, and TSQL to help pay 
    the bills. Between then and now, I can't decide whether I've learned a great deal more or only improved incrementally.
    </p>
    <h2>Learning SQL can be hard.</h2>
    <p>
    I attended a college class, read books, watched live webcasts like <a href="http://www.sqllunch.com/AboutUs.aspx">SQLLunch</a> and 
    <a href="http://www.sqlpass.org/Events/24HoursofPASS.aspx">24 Hours of PASS</a>, attended <a href="http://www.sqlsaturday.com/">SQLSaturday</a> 
    events, and learned from far more knowledgeable <a href="http://lessthandot.com">friends</a>.
    </p>
    <p>
    All of this helped, but when someone asks me how to learn SQL, I still don't have a good answer.
    </p>
    <h2>Hands On Learning</h2>
    <p>
    Of all of the many places I learned from, what made it all stick and make sense was putting hands-on-keyboard and using all
    the new things I was learning. Practice problems, programming challenges, and real production problems made all of those 
    lessons real.
    </p>
    <h2>The Goal...</h2>
    <p>
    The goal of this site is to provide a guided, hands-on experience. A way to learn the basics or advance our skills through
    actual hands-on-keyboard experience. A mix of guidance and experimentation with a real SQL database evaluating our progression.
    </p>
    <h2>Why?</h2>
    <p>
    I believe strongly in personal skill development and have always wished there was something like this being actively developed.
    A site I could point developers to when they're trying to advance their SQL skills, somewhere more advanced users can try things
    like windowing functions with some guidance and clear explanations. A hands=-on resource to complement the videos, books, blogs and 
    such.
    </p>
    <p>
    For now I'm paying for this site out of pocket and working on it in my spare time. I provide
    a lot of information on the @Html.ActionLink("technology", "Tech", "About") and will probably open up the source later on as well.
    </p>
</div>

SQLisHard/Views/About/Tech.cshtml
@{
    ViewBag.Title = "Learning SQL - The Tech";
    ViewBag.PageDescription = "The SQLisHard.com site and online query tools is built on a number of technologies, including Windows Azure, ASP.Net, HTML, and JavaScript.";

}
<div class="about">
    <div class="banner">
        <h1>SQL is Hard</h1>
        <ul>
            <li>@Html.ActionLink("The Goal","","About")</li>
            <li>@Html.ActionLink("The Exercises","Exercises","About")</li>
            <li class="selected">@Html.ActionLink("The Tech","Tech","About")</li>
@*            <li>@Html.ActionLink("Updates","Updates","About")</li>*@
        </ul>
    </div>
    <h2>Welcome to the Cloud</h2>
    <p>
    The SQLisHard application runs in <a href="http://www.windowsazure.com/en-us/" title="Windows Azure">Windows Azure</a> 
    and executes queries against sample data that resides in an
    <a href="http://msdn.microsoft.com/en-us/library/windowsazure/ee336279.aspx" title="Azure SQL Database">Azure SQL Database</a>. 
    The site runs as a shared website in <a href="http://www.windowsazure.com/en-us/home/scenarios/web-sites/" title="Azure Web Sites">Windows Azure Web Sites</a>.
    </p>
    <h2>The App</h2>
    <p>
    The application is an <a href="http://www.asp.net/" title="ASP.Net">ASP.Net</a> application, using both 
    <a href="http://www.asp.net/mvc" title="ASP.Net MVC">MVC</a> and <a href="http://www.asp.net/web-api" title="ASP.Net Web API">Web API</a>
    on the server-side with the <a href="http://www.codethinked.com/squishit-the-friendly-aspnet-javascript-and-css-squisher" title="SquishIt library">SquishIt</a>
    library to manage CSS and JavaScript resources. The client-side uses <a href="http://html5boilerplate.com/">HTML5 Boilerplate</a> and javascript libraries like 
    <a href="http://jquery.com/" title="jQuery library">jQuery</a>, <a href="http://knockoutjs.com/" title="knockout.js library">knockout.js</a> 
    with <a href="https://github.com/ifandelse/Knockout.js-External-Template-Engine/blob/master/README.md" title="koExternalTemplateEngine on github">koExternalTemplateEngine</a>, 
    and <a href="http://modernizr.com/" title="modernizr library">modernizr</a>. Behind the scenes, results and errors are collected and logged to cloud logging services, where 
    they can be evaluated, charted, and improved from.
    </p>
    <h2>On Demand Deployment</h2>
    <p>
    The build and deployment process is automated; a custom build setup in 
    <a href="http://www.jetbrains.com/teamcity/" title="Check out TeamCity">TeamCity</a> watches for code changes, 
    running unit and integration tests (<a href="http://www.nunit.org/" title="Nunit">Nunit</a>, 
    <a href="http://docs.seleniumhq.org/" title="Selenium WebDriver">Selenium</a>, 
    <a href="http://www.specflow.org/specflownew/" title="SpecFlow BDD">SpecFlow</a>,
    <a href="http://pivotal.github.io/jasmine/" title="Jasmine">Jasmine</a>),
    and deploying both local test environments 
    and the production environment.
    </p>
    <p>
    This reduces the friction. I can tweak the interface or add a feature and not have to slow down and copy files somewhere.
    </p>
    <h2>More Detail to Come</h2>
    <p>
    This wasn't intended to read like a tech demo, but I enjoy working with each of these technologies and thought 
    I should call them out. I intended to blog more on them when I have time over on <a href="http://lessthandot.com">LessThanDot</a>.
    </p>
    
</div>