SQLisHard/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SQLisHard.Controllers
{
    public class AboutController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Exercises()
		{
			return View();
		}

		public ActionResult Tech()
		{
			return View();
		}

    }
}

SQLisHard/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SQLisHard.Controllers
{
    public class ExerciseController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Old()
		{
			return View();
		}

    }
}

SQLisHard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SQLisHard.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

		public ActionResult Signout()
		{
			FormsAuthentication.SignOut();

			return View("Index");
		}

		public ActionResult Exception()
		{
			throw new Exception("MVC Exception Message");
		}
    }
}

SQLisHard/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Let's Get Started";
    ViewBag.PageDescription = "Learning SQL can be tough. SQLisHard.com is an interactive set of exercises to help you learn SQL online using hands-on exercises with Microsoft TSQL on SQL Server.";
    ViewBag.Keywords = "Learn SQL Online";
}

<div class="banner">
<h1>SQL is Hard</h1>
<div class="about">
    <p>Learning SQL can be daunting, despite the incredible availability of reference materials. Sometimes the best way to learn is to get your hands dirty.</p>
    <p>SQLisHard.com provides guided, interactive exercises to help you learn T-SQL against a live SQL Server database.</p>
    <a href="@Url.Action("Index","Exercise")"><img src="@Url.Content("~/Content/Screenshot.png")" title="Sample screenshot" style="border: 1px solid #DDDDDD;" /></a><br />
    <a href="@Url.Action("Index","Exercise")" class="call-to-action">Let's get started <i class="icon-arrow-right"></i></a>
</div>
    <p style="width: 700px; margin: 20px auto;">
        SQLisHard.com is a work in progress. The first set of exercises focuses on SELECTing data, from basic queries to JOINs and aggregation, and is a <a href="@Url.Action("Exercises","About")">work in progress</a>.
        I will continue to expand these, adding more advanced sets of exercises as time allows.</p>
</div>